### ISSUE TITLE
Future pose estimation when the moving platform is steady.[Not issue]

### ISSUE THREAD

**Issue by maharshi114** [AprilRobotics/apriltag#119]
Can we estimate the future pose if my April tag in the FOV of the camera?

For Example, apriltag in FOV and showing the following parameter
X: 100mm
Y: 0 mm
Z: 2500 mm
Yaw: 180 Degree 
Pitch: 0.5 Degree 
Roll: 0.5 Degree 

now if I turn my camera platform by +30 Degree of yaw (180 + 30), what is my next X and Y coordinates should be?  Can someone explain the math behind it. 

Thanks and Appreciating your efforts.

**Comment by mkrogius** [comment]
I can't help in depth, but I can try to point you in the right direction. What you want is called a coordinate frame transformation, because you want to transform between the coordinate frame at the previous timestep and your current coordinate frame. You can try googling this keyword, but material on this subject is pretty disorganized. I did find this pdf here: http://blog.espol.edu.ec/matg1049/files/2019/08/Doc2019_coordenadas_robot.pdf

There are also textbooks that include this topic, one of which is Robot Modeling and Control by Spong
