### ISSUE TITLE
bloom release 3.3

### ISSUE THREAD

**Issue by christian-rauch** [AprilRobotics/apriltag#269]
Can we get a new release for the 3.3 version? I think this now has to happen via the rolling release repo at https://github.com/ros2-gbp/apriltag-release. For ROS 1, I think we only need to support `noetic`. For ROS 2, the LTS versions `foxy` and `humble` should be sufficient. I am not sure how the release to `rolling` works. Could we also just release to `rolling` and it gets automatically released to all other stable distributions?

**Comment by wxmerkt** [comment]
Given considerations to drop the vendored apriltag altogether due to it becoming available upstreamed via the distros (https://github.com/ros/rosdistro/issues/35273), I'll ask first before making a release of 3.3

And yes, if we release to rolling before it gets copied over to iron it will automatically be in the future iron release.
