### ISSUE TITLE
Border text an issue?

### ISSUE THREAD

**Issue by BryanStuurman** [AprilRobotics/apriltag#272]
I have some apriltags which are being intermittently detected, they have text in the white border (as pictured below) - is this problematic? should the border be clean, and if so for what distance?
![image](https://user-images.githubusercontent.com/87621617/222818937-15bc534a-7020-4821-baa8-b0fbed8f8e40.png)

**Comment by christian-rauch** [comment]
Yes. The borders have to be clean white so that the edges can be detected. You could try to reduce the size of the text or use a lighter shade of grey. If in doubt, use the [templates](https://github.com/AprilRobotics/apriltag-imgs) or the [tag-generation scripts](https://github.com/AprilRobotics/apriltag-generation).

**Comment by BryanStuurman** [comment]
Thanks for the fast response! I'll let my team know.
