### ISSUE TITLE
Question: How to process moving frames?

### ISSUE THREAD

**Issue by onthegrid007** [AprilRobotics/apriltag#340]
Hello devs,

I am working with a DepthAI camera from Luxonis and this is by far the fastest and most accurate April tag implementation I have found so far. My problem is with even the slightest camera movement I assume the frames are blurry and fails to detect even the most obvious less than 6 inches away tag. I have tried the built in depthai-core april tag tracker and it is much worse than this implementation. My question is: Is there a way to almost overlay the frames to reduce blurriness to track the tags during movement or by some other implementation of possibly keeping track of the last April tags found with their location and rotation and possibly use an algorithm to track it over frames? There is also a built in 3axis accelerometer built into the camera and raw xyz and quat if this helps at all. I'm looking at this for a personal project any help would be appreciated...

**Comment by mkrogius** [comment]
Can you post an example image that fails to be detected, please?

**Comment by onthegrid007** [comment]
It's a live video feed. Let me make some modifications and see if I can't grab a few stills

**Comment by onthegrid007** [comment]
![ezgif-frame-010](https://github.com/AprilRobotics/apriltag/assets/43478178/8fd24439-7c0c-4e34-8f7e-33f3ad8210a4)
![ezgif-frame-011](https://github.com/AprilRobotics/apriltag/assets/43478178/8f655e0f-18e8-4fe9-a850-b4a184b677df)
![ezgif-frame-012](https://github.com/AprilRobotics/apriltag/assets/43478178/541eb83f-09c2-4382-8b61-3fb44ea105b1)
3 Frames in order

**Comment by mkrogius** [comment]
The middle frame has too much motion blur for the apriltag to be detected. I'd suggest either putting the apriltag closer to the camera or reducing the exposure in order to get a detection. I don't think frame averaging will be helpful.

This repo is only focused on single frame detection, not tracking, so it can't help with implementing a tracking solution. That said, using the IMU to continue tracking the camera when the apriltag is blurry, would probably work well

**Comment by onthegrid007** [comment]
Thank you
