### ISSUE TITLE
Need to use the library in detecting april tags by my Robot

### ISSUE THREAD

**Issue by VigneshS1993** [AprilRobotics/apriltag#79]
Dear Apriltag Robotics team
I am a student and I am currently having a bot (build with Raspberry Pie) which has many functionalities. One among them being decoding different symbols (Bar codes, QRCodes etc), Due to the recent advent of April tags, I am fancied to use the same in my robot. I have used OpenCV and zbar to detect and decode QR tags. Can you suggest me a way to decode the April tags as well and how to use your library in the same ?

**Comment by vigisa93** [comment]
Dear Apriltag Robotics team
I am a student and I am currently having a bot (build with Raspberry Pie) which has many functionalities. One among them being decoding different symbols (Bar codes, QRCodes etc), Due to the recent advent of April tags, I am fancied to use the same in my robot. I have used OpenCV and zbar to detect and decode QR tags. Can you suggest me a way to decode the April tags as well and how to use your library in the same ?

**Comment by xiongdahua555** [comment]
compile install and using

**Comment by mkrogius** [comment]
Please follow the instructions on this github for installing and using the library. If you have further, more specific questions, feel free to post a follow up issue.
