### ISSUE TITLE
tuning apriltag_quad_thresh_params

### ISSUE THREAD

**Issue by maorp** [AprilRobotics/apriltag#81]
Hey, im struglling with detection of frames that look like should've been easy for detection.
im thinking about playing with apriltag_quad_thresh_params but cant find any example for that.
i can upload the debug images if anyone wants a look.
currently using:
	apriltag_detector_t *td = apriltag_detector_create();
	apriltag_detector_add_family(td, tf);
	td->quad_decimate = 1.f;
	td->quad_sigma = 0.5f;
	td->nthreads = 1;
	td->refine_edges = 0;

![stream001_00008RGB](https://user-images.githubusercontent.com/11231999/78019400-55155880-7358-11ea-852c-ae0b881a4312.png)

**Comment by xiongdahua555** [comment]
I think the problem is：td->quad_sigma =0.5，and your image is blurry。

**Comment by mkrogius** [comment]
The problem here is that the tags have been cut out/printed incorrectly so that in the image you have uploaded, the border is ~1pixel wide, and it is blurred with the neighboring pixels such that it does not show up as white.. The outer white border should be cut out with the same width as the black border.
